# Numpy Experiment

In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5,6,7,8]
print(a)
print(type(a))

[1, 2, 3, 4, 5, 6, 7, 8]
<class 'list'>


In [3]:
a = np.array([1,2,3,4,5,6,7,8])
print(a)
print(type(a))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


# ndim

In [4]:
a.ndim

1

In [5]:
arr_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2D)
print(type(arr_2D))
print(arr_2D.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
2


In [13]:
arr_3D = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(arr_3D)
print(type(arr_3D))
print(arr_3D.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>
3


In [26]:
arr_5D = np.array([[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3],[4,4,4,4,4],[5,5,5,5,5]])
print(arr_5D)
print(type(arr_5D))
print(arr_5D.ndim)  # 5 X 5 matrix

[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]
<class 'numpy.ndarray'>
2


In [27]:
arr = np.array([[[0,0],[1,1]],[[2,2],[3,3]],[[4,4],[5,5]]])
print(arr)
print(type(arr))
print(arr.ndim)    #  '3 X 2 X 2'  matrix

[[[0 0]
  [1 1]]

 [[2 2]
  [3 3]]

 [[4 4]
  [5 5]]]
<class 'numpy.ndarray'>
3


# size(show element no)

In [30]:
arr_2D.size

9

In [31]:
arr.size

12

# shape show no of rows

In [35]:
arr_2D.shape

(3, 3)

In [36]:
arr_5D.shape

(5, 5)

In [34]:
arr.shape

(3, 2, 2)

# dtype :- show data type of array

In [37]:
arr.dtype

dtype('int32')

In [38]:
a1 = np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7,8.8])
print(a1)
print(a1.dtype)

[1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8]
float64


In [43]:
a1 = np.array([[1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1]])
print(a1)
print(a1.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int32


In [44]:
a2 = np.array([[0,0,0],[0,0,0],[0,0,0]])
print(a2)
print(a2.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
int32


# ones() and zeros()  with dtype int str

In [45]:
b1 = np.ones((4,4))
print(b1)
print(b1.dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64


In [48]:
b1 = np.zeros((3,3),dtype=int)
print(b1)
print(b1.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
int32


In [51]:
b1 = np.ones((4,4),dtype=str)
print(b1)
print(b1.dtype)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]
<U1


In [49]:
b1 = np.zeros((3,3),dtype=str)
print(b1)
print(b1.dtype)

[['' '' '']
 ['' '' '']
 ['' '' '']]
<U1


In [53]:
b1 = np.ones((4,4),dtype=bool)
print(b1)
print(b1.dtype)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
bool


In [52]:
b1 = np.zeros((3,3),dtype=bool)
print(b1)
print(b1.dtype)

[[False False False]
 [False False False]
 [False False False]]
bool


# empty

In [55]:
em_mx = np.empty((4,4))  # it give garbage value
em_mx

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# arange()

In [ ]:
# np.arange(start_value,end_value,step)

In [56]:
ar_1d = np.arange(13)
ar_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [57]:
ar_1d = np.arange(2,13)
ar_1d

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# linespace()

In [58]:
# np.arange(start_value,end_value,no of value b\t start to end)

In [61]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [62]:
np.linspace(100,150,3)

array([100., 125., 150.])

# reshape()

In [65]:
a = np.linspace(1,10,25)
a

array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625,
        4.   ,  4.375,  4.75 ,  5.125,  5.5  ,  5.875,  6.25 ,  6.625,
        7.   ,  7.375,  7.75 ,  8.125,  8.5  ,  8.875,  9.25 ,  9.625,
       10.   ])

In [67]:
arr1 = a.reshape(5,5)
arr1

array([[ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ],
       [ 2.875,  3.25 ,  3.625,  4.   ,  4.375],
       [ 4.75 ,  5.125,  5.5  ,  5.875,  6.25 ],
       [ 6.625,  7.   ,  7.375,  7.75 ,  8.125],
       [ 8.5  ,  8.875,  9.25 ,  9.625, 10.   ]])

In [76]:
arr2 = np.arange(1,13).reshape(3,2,2)
arr2

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

# ravel()

In [77]:
arr2 = np.arange(1,13).reshape(3,2,2)
arr2

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [78]:
arr2.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose() or T

In [79]:
arr = np.linspace(1,10,25).reshape(5,5)
arr

array([[ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ],
       [ 2.875,  3.25 ,  3.625,  4.   ,  4.375],
       [ 4.75 ,  5.125,  5.5  ,  5.875,  6.25 ],
       [ 6.625,  7.   ,  7.375,  7.75 ,  8.125],
       [ 8.5  ,  8.875,  9.25 ,  9.625, 10.   ]])

In [80]:
arr.transpose()  # it convert row to colum

array([[ 1.   ,  2.875,  4.75 ,  6.625,  8.5  ],
       [ 1.375,  3.25 ,  5.125,  7.   ,  8.875],
       [ 1.75 ,  3.625,  5.5  ,  7.375,  9.25 ],
       [ 2.125,  4.   ,  5.875,  7.75 ,  9.625],
       [ 2.5  ,  4.375,  6.25 ,  8.125, 10.   ]])

In [81]:
arr.T   # it convert row to colum

array([[ 1.   ,  2.875,  4.75 ,  6.625,  8.5  ],
       [ 1.375,  3.25 ,  5.125,  7.   ,  8.875],
       [ 1.75 ,  3.625,  5.5  ,  7.375,  9.25 ],
       [ 2.125,  4.   ,  5.875,  7.75 ,  9.625],
       [ 2.5  ,  4.375,  6.25 ,  8.125, 10.   ]])

# mathematical operation using numpy

In [82]:
arr2 = np.arange(1,10).reshape(3,3)
arr3 = np.arange(1,10).reshape(3,3)
print(arr2)
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [83]:
print(arr2 + arr3)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [86]:
print(arr2 - arr3)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [84]:
print(arr2 * arr3)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [85]:
print(arr2 ** arr3)

[[        1         4        27]
 [      256      3125     46656]
 [   823543  16777216 387420489]]


In [87]:
print(arr2 / arr3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [88]:
print(arr2 @ arr3) # matrix multification

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [90]:
arr2.dot(arr3)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [92]:
np.add(arr2,arr3)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [94]:
np.subtract(arr2,arr3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [96]:
np.multiply(arr2,arr3)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [97]:
np.divide(arr2,arr3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])